### ISSUE TITLE
Compatibility with SteamDeck

### ISSUE THREAD

**Issue by Enegma1** [d3xMachina/FFPR-Fix#3]
The fix does not seem to work on the Steam Deck - the config folders and files do not generate after starting the game. Copying over the relevant folders from PC also does not work.

**Comment by d3xMachina** [comment]
On Steam OS, you need to add `export WINEDLLOVERRIDES="winhttp=n,b"; %command%` to the launch options.

![image](https://github.com/user-attachments/assets/4b9c426c-8a7b-4188-bce5-15baecfccbe6)

**Comment by Enegma1** [comment]
Adding the launch options generated the additional folders. However the config folder is missing d3xMachina.ffpr_fix.cfg needed to tweak the settings. Only BepIn.cfg is in the folder.

**Comment by Enegma1** [comment]
Adding the launch options generated the additional folders. However the config folder is missing d3xMachina.ffpr_fix.cfg needed to tweak the settings. Only BepIn.cfg is in the folder.

**Comment by Enegma1** [comment]
I should also add that copying the missing cfg file from my PC did not resolve the issue as well.

**Comment by d3xMachina** [comment]
Can you show your folder structure with the files ?
You should have winhttp.dll and the BepInEx folder next to the game executable ("FINAL FANTASY VI.exe" for example).
You should also have "FFPR_Fix.dll" in "BepInEx\plugins\".

**Comment by Enegma1** [comment]
I found the issue - my plugins folder was empty! Copying over FFPR_Fix.dll from my PC to the deck got it working.

All other files were in place and I was using the latest version provided. I basically had to copy over the missing cfg and the above dll for the fix to work. Thanks! Though I am curious why they did not generate when I started up the games.

**Comment by d3xMachina** [comment]
Glad it works. The cfg didn't generate because the FFPR Fix plugin which generate its own config was missing.
